# Generated by Django 5.2 on 2025-08-30 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
