# Generated by Django 5.2 on 2025-08-30 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_transaction', models.CharField(choices=[('Cash', 'Cash'), ('PhonePe', 'PhonePe'), ('GPay', 'GPay'), ('Paytm', 'Paytm'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rent_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='base.rentplan')),
                ('roommate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
