# Generated by Django 5.2 on 2025-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
