# Generated by Django 5.2 on 2025-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_rentplan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentplan',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
