# Generated by Django 5.2 on 2025-08-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_rentplan_monthly_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rentplan'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
