# Generated by Django 5.2 on 2025-08-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_room_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
    ]
